name: Qualcomm Preflight Checks
on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ development ]
  workflow_dispatch:

permissions:
 contents: read
 security-events: write

jobs:
  qcom-preflight-checks:
    uses: qualcomm-linux-stg/qcom-reusable-workflows/.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml@main
    with:
        enable-armor-checkers: true
